filter:
    paths: [src/*]
    excluded_paths: [tests/*]
checks:
  php:
    code_rating: true
    remove_extra_empty_lines: true
    remove_php_closing_tag: true
    remove_trailing_whitespace: true
    fix_use_statements:
      remove_unused: true
      preserve_multiple: false
      preserve_blanklines: false
      order_alphabetically: true
    fix_php_opening_tag: true
    fix_linefeed: true
    fix_line_ending: true
    fix_doc_comments: true
    non_commented_empty_catch_block: false
    encourage_single_quotes: true
    unused_parameters: false
tools:
  external_code_coverage:
    timeout: 600
    runs: 3
